name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python -m pip install -e .
    - name: Test with pytest
      run: pytest -ra --cov .
    - name: Cache deps
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-